#!/bin/bash

cleanup() {
  test -d ./projector/ && rm -rf ./projector/
}

error() {
  cleanup

  echo "docs: $@"
  exit 1
}

bash $(find ./doc/example/ -type f) || error 'some doc examples are exiting with non zero exit code'

cleanup

mash ./doc/README.md > README.md
