#!/bin/bash

function url() {
  local file="$1"
  local branch="${2:-master}"

  echo "https://raw.githubusercontent.com/bas080/projector/$branch/$file"
}

function path() {
  echo "$HOME/$1"
}

function install() {
  local version="$1"

  download "$(url projector.sh $version)" "$(path .projector)"

  test -f "$HOME/.zshrc" && download "$(url projector_zsh.sh $version)" "$(path .projector_zsh)" && \
    setup_env "$HOME/.zshrc"  "source ~/.projector_zsh"

  test -f "$HOME/.bashrc" && download "$(url projector_bash.sh $version)" "$(path .projector_bash)" && \
    setup_env "$HOME/.bashrc" "source ~/.projector_bash"
}

function download() {
  local url="$1"
  local filename="$2"

  echo "$url > $filename"
  curl -s -f "$url" > "$filename"
}

function setup_env() {
  local source_file="$1"
  local source_command="$2"

  test ! -f $source_file && return 0

  grep -q "$source_command" "$source_file" || \
    echo "$source_command" >> "$source_file"
}

install "$@" && echo succes || echo failure
