#!/bin/bash

set -e

source ./projector.sh

equals() {
  local expected="$1"
  local actual=""

  test $# -eq 1  && {
    local temp="$(mktemp)"
    cat - > $temp
    actual="$(cat $temp)"
  } || actual="$2"

  test "$expected" == "$actual" || (echo -e "[expected] \"$expected\"\n[actual] \"$actual\"" > /dev/stderr && return 1)
}

tests() {
  before_all && \
    cat - | while read a_test; do
      before_each && \
      echo "[test] $a_test"
      eval "$a_test" && \
        echo "[succes] $a_test" || \
        echo -e "\033[0;31m[failure]\033[0m $a_test"
    done

  after_all
}

# lifecycles

before_all() {
  test_dir="$(mktemp -d)"

  cd $test_dir
}

after_all() {
  return 0
}


before_each() {
  test_dir="$(mktemp -d)"
  mkdir $test_dir/child
}

# test helpers

test_cd() {
  cd "$@" && \
    projector_prompt
}

# tests

sources_when_a_bash_project_is_created() {
  test_cd $test_dir | equals ""

  touch "$test_dir/.bash_project" && \
    test_cd $test_dir | equals "projector: sourced $test_dir/.bash_project"
}

sources_the_parent_from_child() {
  touch $test_dir/.bash_project

  test_cd $test_dir/child | \
    equals "projector: sourced $test_dir/.bash_project"
}

does_not_source_when_already_sourced() {
  touch $test_dir/.bash_project

  local output="$(test_cd / && test_cd $test_dir && test_cd $test_dir)"

  equals "$output" "projector: sourced $test_dir/.bash_project"
}

sources_when_file_has_modified() {
  touch $test_dir/.bash_project && \
    equals \
    "$(test_cd $test_dir; sleep 1; touch $test_dir/.bash_project; projector_prompt)" \
    "projector: sourced $test_dir/.bash_project
projector: sourced $test_dir/.bash_project"
}

sources_when_child_has_bash_project() {
  touch $test_dir/child/.bash_project && \
    test_cd $test_dir/child | \
    equals "projector: sourced $test_dir/child/.bash_project"
}

sources_when_moving_back_to_parent() {
  test_cd / | equals "" || return 1

  touch $test_dir/.bash_project

  test_cd $test_dir | \
    equals "projector: sourced $test_dir/.bash_project"
}

echo """sources_when_a_bash_project_is_created
does_not_source_when_already_sourced
sources_the_parent_from_child
sources_when_child_has_bash_project
sources_when_moving_back_to_parent
sources_when_file_has_modified""" | shuf | tests
